### ISSUE TITLE
Contextual footer: in some pages the last section has a bottom border and margin bottom (needs to be removed)

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#165]

**Comment by pmahnke** [comment]
@yaili I think I fixed this... can you look again? at least the dotted border is gone.

**Comment by yaili** [comment]
I can't see it. Do you know which pages it was on?

**Comment by pmahnke** [comment]
this was the fix... anything in phone or tablet

On 10 April 2016 at 21:34, Inayaili de León Persson <
notifications@github.com> wrote:

> I can't see it. Do you know which pages it was on?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ubuntudesign/ubuntu-vanilla-theme/issues/165#issuecomment-208064152>
>



-- 
Peter Mahnke
Head of Web development

Canonical
0796 108 4362
peter.mahnke@canonical.com

**Comment by magdalena-mirowicz** [comment]
this is still not fixed on management, about and support pages
